### ISSUE TITLE
Couple of UI changes and bugs noted

### ISSUE THREAD

**Issue by frinzekt** [our-lab-training/olt-frontend#31]
- Give Induction better wording for the induction
- Training is a subset of induction (Clarification)
- Scroll up while opening induction
- inconsistency on the induction process
       - eg. Sophie, Amit (did the induction, but not ticked off), Frinze (did the induction, and ticked off)
       - confirmation
       - flag -> cannot sign off when something is missing and notification of what is missing
- code cleanup + reorganization
- quizzes module
- update packages
- provide feedback modal close should be at the top (intuitive factor)
- put some shadings on tabs that expands in on the left hand side to show which will expand and which will go somewhere
- no way to create hidden files (perhaps remving show/hide hidden files)
- adding account errors, and tries again and works (unknown bug? #33)
- what is the process of creating a new group/organisation???
- cannot do "require previous training"
        - bug exploration:  step name is not showing up
        - bug of showing irrelevant fields"require previous training" is -> select step type "require previous training" -> select training module  any -> select step type "review/complete from safety binder" -> select document any -> select "require previous training" -> this will show up with 2 new fields (Step name and cooldown duration)
![image](https://user-images.githubusercontent.com/44391389/92196803-ae069100-eea2-11ea-9ace-ee32db4e8ebb.png)

![image](https://user-images.githubusercontent.com/44391389/92196828-bfe83400-eea2-11ea-831e-de648b1d4756.png)

- UI problems for long text items (consider "..." + hover/tooltip)
- cannot create Training + No Notification
![image](https://user-images.githubusercontent.com/44391389/92196779-9f1fde80-eea2-11ea-91a9-896b4832945b.png)
The way to successfully create training is search until you get 
- (no way to edit Training) edit: You can edit training and save it locally but will not reflect in server
```
o {type: "FeathersError", name: "BadRequest", message: "Validation failed: steps.1.link: Invalid link provided.", code: 400, className: "bad-request", …}
className: "bad-request"
code: 400
data: undefined
errors: {steps.1.link: {…}}
message: "Validation failed: steps.1.link: Invalid link provided."
name: "BadRequest"
type: "FeathersError"
stack: "BadRequest: Validation failed: steps.1.link: Invalid link provided.↵    at new o (https://ourlab.training/js/chunk-vendors.52e51c18.js:121:4753)↵    at Object.T [as convert] (https://ourlab.training/js/chunk-vendors.52e51c18.js:121:6526)↵    at p.<anonymous> (https://ourlab.training/js/chunk-vendors.52e51c18.js:1488:259456)↵    at p.onack (https://ourlab.training/js/chunk-vendors.52e51c18.js:40:64230)↵    at p.onpacket (https://ourlab.training/js/chunk-vendors.52e51c18.js:40:63591)↵    at p.<anonymous> (https://ourlab.training/js/chunk-vendors.52e51c18.js:66:121571)↵    at p.r.emit (https://ourlab.training/js/chunk-vendors.52e51c18.js:80:588137)↵    at p.ondecoded (https://ourlab.training/js/chunk-vendors.52e51c18.js:80:609094)↵    at p.<anonymous> (https://ourlab.training/js/chunk-vendors.52e51c18.js:66:121571)↵    at p.r.emit (https://ourlab.training/js/chunk-vendors.52e51c18.js:80:588137)"
__proto__: i
```
![image](https://user-images.githubusercontent.com/44391389/92197227-bf9c6880-eea3-11ea-846b-41cbc1df083f.png)
- no way to delete training
- (needs clarification) what should happen when a new step is added in the training but the user has already completed the training?
- CORS problem with uploading files
![image](https://user-images.githubusercontent.com/44391389/92197686-1191be00-eea5-11ea-9adb-5070fae2262b.png)
- when initially publishing, the "analytics", "view" should not be present
- there is no way to edit "SHL 1.53 Lab Training". Pressing the pencil/edit icon will show
![image](https://user-images.githubusercontent.com/44391389/92208172-43af1a00-eebd-11ea-945d-38876289128d.png)
this is the error message of that 
![image](https://user-images.githubusercontent.com/44391389/92208223-59bcda80-eebd-11ea-92ee-4dcdbc8b34e2.png)
- unpublished training can be seen by normal users, but when clicked, a window opens and closes.

**Comment by frinzekt** [comment]
Whenever deleting an item from the safety binder, it will delete the item above it
